config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#home"
  resources:articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources:categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum:3, maximum: 50 }
    validates :description, presence: true, length: {minimum:10, maximum: 300 }
    
    
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  

end

app/models/user.rb
class User < ApplicationRecord
    #dependent if we destroy our user it will also destroy all articles that user has been created
    has_many :articles, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :username, presence:true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 105}, uniqueness: { case_sensitive: false }, 
    #chek the validity of email format
    format: { with: VALID_EMAIL_REGEX }
    validates :password, presence:true, length: { minimum: 5, maximum: 50}
    has_secure_password


end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #helper metode mogu koristiti u viewima ne u konrolerima, 
    #zbog toga sam napravio helper_method
    helper_method :current_user, :logged_in?

    def current_user #ovo mi je ulogovani user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            flash[:danger] = "You must be logged in to perform that action"
            redirect_to root_path
        end
    end







end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "bobivankenobi", password: "bobicar92", except: [:index, :show]
  
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
      @articles = Article.paginate(page: params[:page], per_page: 3)
  end
  
  
  def new
    @article=Article.new
  end
  
  def create
    #render plain: params[:article].inspect
    @article=Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
    else render 'new'
    end
  end

  def show
      
  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  def edit #display form for the existing method,template

  end

  def update
    if @article.update_attributes(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end


  private

  def set_article 
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: []) 
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "You can only edit or delete your own articles"
      redirect_to root_path
    end
  end


end






   

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :set_category, only: [:show]
  before_action :require_admin, except: [:index, :show]

  def index
    
    @categories = Category.paginate(page: params[:page], per_page: 4)
  end

  def new
    @category=Category.new
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  def create
    @category=Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created"
      redirect_to categories_path
    else render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end
    
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  private

  def set_category
    @category= Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admins can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id
          flash[:success] = "You have successfully logged in"
          redirect_to user_path(user)
      else
          flash.now[:danger] = "There was something wrong with your login information"
          render 'new'
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 2)
  end

  def new
    @user=User.new
  end

  def create
    #render plain: params[:article].inspect
    @user=User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the alpha blog #{@user.username}"
      redirect_to user_path(@user)
      else render 'new'
    end
  end

  def edit #display form for the existing method,template
  end

  def update 
    if @user.update_attributes(user_params)
      flash[:notice] = "User was successfully updated"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page: params[:page], per_page: 3)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User andall articles created by user have been deleted"
    redirect_to users_path
  end
  
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform this action"
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options = { size: 80})

        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        
        size = options[:size]
        
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        
        image_tag(gravatar_url, alt: user.username, class:"img-circle")
        
        end
end

app/views/articles/_article.html.erb
<div class="row rowindex">
  <div class="card col-sm-8 bg-secondary offset-sm-2">
    <div class="card-body">
      <%= link_to article.title, article_path(article) %>
        <br/>
        <%= article.description %>
          <br/>
          <div class="created">
            <small>Created by:
              <%= link_to "#{article.user.username}", user_path(article.user) if article.user %>,
                <%= time_ago_in_words(article.created_at) %> ago, last updated:
                  <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>

          <% if article.categories.any? %>
            <p>Categories: <%= render article.categories %></p>
          <% end %>
          
          <% if logged_in? && ( current_user == article.user || current_user.admin? ) %>
            <%= link_to "Edit this article", edit_article_path(article), class: "btn btn2 btn-xs btn-primary" %>
            <%= button_to "Delete this article", article_path(article), method: :delete,
              data: { confirm: "Are you sure you want to delete the article?"},
              class: "btn btn2 btn-xs btn-danger" %>
          <%end%>
    </div>
  </div>

</div>

app/views/articles/_form.html.erb
<%= render "shared/errors", obj:@article %>
<%= form_for @article, :html => { id:"form-new"}  do |f| %>
  <div class="form-group  ">
    <div class="row">
      <div class="col-sm-2">
        <%= f.label :title,class:" col-form-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :title,class:"form-control", placeholder:"Title of article" %>
      </div>
    </div>
  </div>
  <div class="form-group  ">
    <div class="row">
      <div class="col-sm-2">
        <%= f.label :description,class:" col-form-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_area :description, class:"form-control", placeholder:"Body of description" %>
      </div>
    </div>
  </div>
  <div class="form-group ">
      <div class="col-sm-10 offset-sm-2 lab ">
        <%= form_for @article do |f| %>
        <%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
        <div class="form-group "><br/><br/>
          <div class="col-sm-4 offset-sm-4">
          <%= f.submit class:"btn btn-primary btn-lg"  %>
        </div>
      </div>
      <% end %>
    </div>
  </div><br/>
  
<% end %>

app/views/articles/edit.html.erb
<h1>Update new article </h1>
<%= render 'form' %>


 
 

app/views/articles/index.html.erb
<h1 align="center">Listing all articles:</h1>

<div class="col-sm-4 offset-sm-4" >
  <%= will_paginate  %>
</div>

<%= render partial: "article", collection: @articles %>

<div class="col-sm-4 offset-sm-4" >
  <%= will_paginate  %>
</div>


 

app/views/articles/new.html.erb
<h1>Create new article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title:
  <%= @article.title %>
</h2>
<div class="card col-xs-8 bg-secondary col-xs-offset-2">
  <div class="card-body">
    <ul class="listing">
      <div class="row">
        <div class="col-sm-4 offset-sm-4 center">
          <% if @article.user %>
            <li>Created by: </li>
            <li>
              <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            </li>
            <li class="article-title">
              <%= link_to @article.user.username, user_path(@article.user) %>
            </li>
            <li>
              <small>
                <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
              </small>
            </li>
        </div>
      </div>
    </ul>
    <% end %>
      <h4 class="center description">
        <strong>Description:</strong>
      </h4>
      <hr>
      <%= simple_format(@article.description) %>
      <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>
      <% end %>
        <div class="article-actions">
          <% if logged_in? && ( current_user == @article.user || current_user.admin? ) %>
            <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn1 btn-xs btn-primary" %>
            <%= button_to "Delete this article", article_path(@article), method: :delete,
              data: { confirm: "Are you sure you want to delete the article?"},
              class: "btn btn1 btn-xs btn-danger" 
            %>
          <%end%>
          <%= link_to "View all articles", articles_path, class: "btn btn1 btn-xs btn-success" %>
        </div>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %> </span>

app/views/categories/_form.html.erb
<%= render "shared/errors", obj:@category %>
<%= form_for @category, :html => { id:"form-new"}  do |f| %>
  <div class="form-group  ">
    <div class="row">
      <div class="col-sm-2">
        <%= f.label :name,class:" col-form-label" %>
      </div>
      <div class="col-sm-10 ">
        <%= f.text_field :name,class:"form-control", placeholder:"Name of category" %>
      </div>
    </div>
  </div>
  
  <div class="form-group ">
    <div class="col-sm-10 offset-sm-5">
      <%= f.submit class:"btn btn-primary btn-lg"  %>
    </div>
  </div>
<% end %>
<div class="link">
  [<%=  link_to "Back to articles listing", articles_path%> ]
</div>

app/views/categories/edit.html.erb
<h1 align="center">Edit Category Name</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>LIsting all categories:</h1>
<div class="col-sm-4 offset-sm-4" >
  <%= will_paginate  %>
</div>
<div class="row ">
  <% @categories.each do |category| %>
    <div class="card col-sm-8 bg-secondary marg bg-info offset-sm-2">
    <div class="card-body">
      <%= link_to "#{category.name}", category_path(category) %><br/>
      <small><%= pluralize(category.articles.count, "article") %></small>
      </div>
      </div>
    <% end %>
    
  
</div>

app/views/categories/new.html.erb
<h1 align="center">Create new category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><%= "Category: " + @category.name %></h1>
<div class="col-sm-3 offset-sm-5" >
  <% if logged_in? and current_user.admin? %>
    <%= link_to "Edit Category Name", edit_category_path(@category),class: "editbutton" %>
  <% end %>
  </div>

<div class="col-sm-4 offset-sm-4" >
  <%= will_paginate @category_articles  %>
</div>

<%= render partial: "articles/article", collection: @category_articles %>

<div class="col-sm-4 offset-sm-4" >
  <%= will_paginate @category_articles %>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy
      <a href="enter in a link here">ALPHA BLOG</a>
      by
      <a href="https://www.facebook.com/profile.php?id=100000588727880">Boban Jankovic</a>
    </small>
    <nav>
      <ul>
        <li>
          <%= link_to "Articles", articles_path %>
        </li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="row">
    <div class="col-sm-10 offset-sm-1">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>
          <%= "#{name}" %>:</strong>
        <%= msg %>

          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
  <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id:"logo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item ">
          <%= link_to "Articles", articles_path,class: "nav-link", id:"Articles" %>
        </li>
        <li>
          <%= link_to "Users", users_path, class:"nav-link", id:"Articles" %>
        </li>
        
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              Actions
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "New Article", new_article_path, class:"dropdown-item" %>
              <% if current_user.admin? %>
                <%= link_to "New Category", new_category_path, class:"dropdown-item" %>
              <%end%>
              <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              Categories
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if current_user.admin? %>
                <%= link_to "New Category", new_category_path, class:"dropdown-item" %>
              <%end%>
              <!--
              ovde ne vidi varijablu @categories vec mora ovako da se napise Category.all
              -->
              <% Category.all.each do |category| %>
              <%= link_to "#{category.name}", category_path(category), class:"dropdown-item" %>
              <% end %>
              <div class="dropdown-divider"></div>
                <%= link_to "All Categories", categories_path, class:"dropdown-item" %>
              </div>
          </li>
        <%end%>

      </ul>
      <% if logged_in? %>
        <li class="nav-item dropdown lists">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            Your profile
            <%= "Admin" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit your profile", edit_user_path(current_user), class:"dropdown-item" %>
              <%= link_to "View your profile", user_path(current_user), class:"dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= button_to "Log out", logout_path, method: :delete,
        data: { confirm: "Are you sure you want to logout"},
        class: "dropdown-item", id:"articles1" %>
          </div>
        </li>
        <%else%>
          <li class="lists">
            <%= link_to "Log in", login_path, class:"nav-link ", id:"articles1" %>
          </li>
          <li class="lists">
            <%= link_to "Sing up", signup_path, class:"nav-link", id:"articles1" %>
          </li>
          <%end%>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %><br/><hr>
    <%= debug(params) if Rails.env.development? %>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-sm-12">
      <div class="card bg-danger">
        <div class="card-body">
          <h2 class="card-title">
            <%= pluralize(obj.errors.count, "error") %> prohibited this article from being saved:</h2>
          <p class="card-text">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li>
                  <%= msg %>
                </li>
                <% end %>
            </ul>
          </p>

        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render "shared/errors", obj:@user %>
  <%= form_for @user, :html => { id:"form-new"}  do |f| %>
    <div class="form-group  ">
      <div class="row">
        <div class="col-sm-2">
          <%= f.label :username,class:" col-form-label" %>
        </div>
        <div class="col-sm-10 ">
          <%= f.text_field :username,class:"form-control", placeholder:"Title of username" %>
        </div>
      </div>
    </div>
    <div class="form-group  ">
      <div class="row">
        <div class="col-sm-2">
          <%= f.label :email,class:" col-form-label" %>
        </div>
        <div class="col-sm-10 ">
          <%= f.email_field :email, class:"form-control", placeholder:"Body of email" %>
        </div>
      </div>
    </div>
    <div class="form-group  ">
      <div class="row">
        <div class="col-sm-2">
          <%= f.label :password,class:" col-form-label" %>
        </div>
        <div class="col-sm-10 ">
          <%= f.password_field :password, class:"form-control", placeholder:"Body of password" %>
        </div>
      </div>
    </div>
    <div class="form-group ">
      <div class="col-sm-10 offset-sm-5">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class:"btn btn-primary btn-lg" )%>
      </div>
    </div>
<% end %>
<div class="link">
  [<%=  link_to "Back to articles listing", articles_path%> ]
</div>

app/views/users/edit.html.erb
<h1>Update your user account</h1>


<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div align="center">
  <%= will_paginate  %>
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-sm-4 offset-sm-4">
          <li>
            <%= link_to gravatar_for(user), user_path(user) %>
          </li>
          <li class="article-title">
            <%= link_to user.username, user_path(user) %>
          </li>
          <li>
            <small>
              <%= pluralize(user.articles.count, "article") if user.articles %>
            </small>
          </li>
          <% if logged_in? and current_user.admin? %>
            <li>
              <%= button_to "Delete this user", user_path(user), method: :delete,
              data: { confirm: "Are you sure you want to delete the user and all their articles?" } %>
            </li>
            <li>
              <%= link_to "Edit this user", edit_user_path(user) %>
            </li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>SignUp for AlphaBlog</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to
  <%= @user.username %>'s page</h1>
<br/>
<br/>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<div class="row">
  <div class="col-sm-4 offset-sm-4 center">
    <%= gravatar_for @user, size: 150 %>
      <br/>
      <br/>
  </div>
</div>
<br/>
<br/>
<h4 align="center">
  <%= @user.username %>'s articles</h4>
<!--obrati paznju na @user_articles stavio sam iz razloga jer drugacije pagination nece 
raditi onda su to 2 razlicite varijable pre je bila user.articles -->
<%= render partial: "articles/article", collection: @user_articles %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>ALPHA BLOG</h1>
  <div class="dugme">
    <%= link_to "Sing up now", signup_path, class: "btn-primary btn-lg btn-xlarge" %>
  </div>
</div>